name: Checkout Demo Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone / checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Show files in repo
      - name: List files
        run: ls

      # Step 3: Show all files including hidden
      - name: List all files
        run: ls -la

      # Step 4: Show current folder path
      - name: Print working directory
        run: pwd