name: Checkout Demo Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4

      - name: List files
        run: ls

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Print node version
        run: node -v 