name: Checkout Demo Workflow

on:
  push:
    branches:
      - "main"

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls

      - name: Setup Node
        uses: actions/setup-node@v5

      - name: Print Node Version
        run: node -v

      - name: Install Dependencies
        run: npm i

      - name: Starting Test
        run: npm run test